manifest:
  remotes:
    - name: joselucassr
      url-base: https://github.com/joselucassr
  projects:
    - name: zmk
      remote: joselucassr
      revision: abnt
      import: app/west.yml
  self:
    path: config
